package com.crossover.techtrial.model;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * DailyElectricity is responsible for electricity generated by a Panel in a day.
 *
 * @author Marcos Barbero
 */
@Entity
@Table(name = "daily_electricity")
public class DailyElectricity implements Serializable {
    private static final long serialVersionUID = -2291797968183794145L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name = "panel_id", referencedColumnName = "id")
    private Panel panel;

    @Column(name = "generated_electricity_sum")
    private Long generatedElectricitySum;

    @Column(name = "generated_electricity_min")
    private Long generatedElectricityMin;

    @Column(name = "generated_electricity_max")
    private Long generatedElectricityMax;

    @Column(name = "generated_electricity_average")
    private Double generatedElectricityAverage;

    @Column(name = "reading_at")
    private LocalDateTime readingAt;

    public DailyElectricity() {
    }

    public DailyElectricity(Panel panel, Long generatedElectricitySum, Long generatedElectricityMin,
                            Long generatedElectricityMax, Double generatedElectricityAverage, LocalDateTime readingAt) {
        this.panel = panel;
        this.generatedElectricitySum = generatedElectricitySum;
        this.generatedElectricityMin = generatedElectricityMin;
        this.generatedElectricityMax = generatedElectricityMax;
        this.generatedElectricityAverage = generatedElectricityAverage;
        this.readingAt = readingAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Panel getPanel() {
        return panel;
    }

    public void setPanel(Panel panel) {
        this.panel = panel;
    }

    public Long getGeneratedElectricitySum() {
        return generatedElectricitySum;
    }

    public void setGeneratedElectricitySum(Long generatedElectricitySum) {
        this.generatedElectricitySum = generatedElectricitySum;
    }

    public Long getGeneratedElectricityMin() {
        return generatedElectricityMin;
    }

    public void setGeneratedElectricityMin(Long generatedElectricityMin) {
        this.generatedElectricityMin = generatedElectricityMin;
    }

    public Long getGeneratedElectricityMax() {
        return generatedElectricityMax;
    }

    public void setGeneratedElectricityMax(Long generatedElectricityMax) {
        this.generatedElectricityMax = generatedElectricityMax;
    }

    public Double getGeneratedElectricityAverage() {
        return generatedElectricityAverage;
    }

    public void setGeneratedElectricityAverage(Double generatedElectricityAverage) {
        this.generatedElectricityAverage = generatedElectricityAverage;
    }

    public LocalDateTime getReadingAt() {
        return readingAt;
    }

    public void setReadingAt(LocalDateTime readingAt) {
        this.readingAt = readingAt;
    }

    @Override
    public String toString() {
        return "DailyElectricityDTO{" +
                "id=" + id +
                ", panel=" + panel +
                ", generatedElectricitySum=" + generatedElectricitySum +
                ", generatedElectricityMin=" + generatedElectricityMin +
                ", generatedElectricityMax=" + generatedElectricityMax +
                ", generatedElectricityAverage=" + generatedElectricityAverage +
                ", readingAt=" + readingAt +
                '}';
    }
}
